apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: basic-nodejs-app
  title: Basic Node.js App
  description: Scaffold a simple Node.js service with CI/CD via Cnoe
  tags:
    - nodejs
    - service
spec:
  owner: team:default/engineering
  type: service

  parameters:
    - title: Project Information
      required:
        - name
        - repoUrl
      properties:
        name:
          type: string
          description: Name of the service
        repoUrl:
          type: string
          description: GitHub repository URL (e.g. github.com/org/repo)

  steps:
    - id: fetch
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
        protectDefaultBranch: true

    - id: register
      name: Register in Backstage
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml
